name: Terraform Kong DevPortal Implementaion

on:
  push:
    branches:
      - main
    paths:
      - 'devportal/**'
env:
  TF_LOG: INFO
  TF_VAR_konnect_personal_access_token: ${{ secrets.KONNECT_PAT }}
  TF_VAR_server_url: "https://us.api.konghq.com"
  TF_VAR_environment: "production"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: latest

    - name: Terraform Init
      working-directory: ./devportal
      run: terraform init

    - name: Terraform Validate
      working-directory: ./devportal
      run: terraform validate

    - name: Terraform Plan
      working-directory: ./devportal
      run: terraform plan -input=false

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      working-directory: ./devportal
      run: terraform apply -auto-approve -input=false
      env:
        KONNECT_PAT: ${{ secrets.KONNECT_PAT }}
